/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * ApiErrorNotFound
 * 
 * <p>Not Found error
 */
@SuppressWarnings("serial")
public class ApiErrorNotFound extends RuntimeException {

    @JsonProperty("status")
    private int status;


    @JsonProperty("error")
    private String error;


    @JsonProperty("code")
    private String code;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("RawResponse")
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public ApiErrorNotFound(
            @JsonProperty("status") int status,
            @JsonProperty("error") @Nonnull String error,
            @JsonProperty("code") @Nonnull String code,
            @JsonProperty("RawResponse") @Nullable HttpResponse<InputStream> rawResponse) {
        super("API error occurred");
        this.status = status;
        this.error = Optional.ofNullable(error)
            .orElseThrow(() -> new IllegalArgumentException("error cannot be null"));
        this.code = Optional.ofNullable(code)
            .orElseThrow(() -> new IllegalArgumentException("code cannot be null"));
        this.rawResponse = rawResponse;
    }
    
    public ApiErrorNotFound(
            int status,
            @Nonnull String error,
            @Nonnull String code) {
        this(status, error, code,
            null);
    }

    public int status() {
        return this.status;
    }

    public String error() {
        return this.error;
    }

    public String code() {
        return this.code;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public Optional<HttpResponse<InputStream>> rawResponse() {
        return Optional.ofNullable(this.rawResponse);
    }

    public static Builder builder() {
        return new Builder();
    }


    public ApiErrorNotFound withStatus(int status) {
        this.status = status;
        return this;
    }


    public ApiErrorNotFound withError(@Nonnull String error) {
        this.error = Utils.checkNotNull(error, "error");
        return this;
    }


    public ApiErrorNotFound withCode(@Nonnull String code) {
        this.code = Utils.checkNotNull(code, "code");
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ApiErrorNotFound withRawResponse(@Nullable HttpResponse<InputStream> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApiErrorNotFound other = (ApiErrorNotFound) o;
        return 
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.error, other.error) &&
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            status, error, code,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ApiErrorNotFound.class,
                "status", status,
                "error", error,
                "code", code,
                "rawResponse", rawResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private int status;

        private String error;

        private String code;

        private HttpResponse<InputStream> rawResponse;

        private Builder() {
          // force use of static builder() method
        }

        public Builder status(int status) {
            this.status = status;
            return this;
        }

        public Builder error(@Nonnull String error) {
            this.error = Utils.checkNotNull(error, "error");
            return this;
        }

        public Builder code(@Nonnull String code) {
            this.code = Utils.checkNotNull(code, "code");
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nullable HttpResponse<InputStream> rawResponse) {
            this.rawResponse = rawResponse;
            return this;
        }

        public ApiErrorNotFound build() {
            return new ApiErrorNotFound(
                status, error, code,
                rawResponse);
        }

    }
}

