/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.Pet;
import org.openapis.openapi.operations.AddPet;
import org.openapis.openapi.utils.Utils;

public class AddPetRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private Pet request;
    private boolean _setterCalled;

    public AddPetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AddPetRequestBuilder request(@Nonnull Pet request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private Pet _buildRequest() {
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AddPetResponse call() throws Exception {
        RequestOperation<Pet, AddPetResponse> operation
              = new AddPet.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
