/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.User;
import org.openapis.openapi.operations.CreateUser;

public class CreateUserRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private User request;
    private boolean _setterCalled;

    public CreateUserRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateUserRequestBuilder request(@Nullable User request) {
        this.request = request;
        return this;
    }

    private User _buildRequest() {
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CreateUserResponse call() throws Exception {
        RequestOperation<User, CreateUserResponse> operation
              = new CreateUser.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
