/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.util.List;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.User;
import org.openapis.openapi.operations.CreateUsersWithListInput;

public class CreateUsersWithListInputRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private List<User> request;
    private boolean _setterCalled;

    public CreateUsersWithListInputRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateUsersWithListInputRequestBuilder request(@Nullable List<User> request) {
        this.request = request;
        return this;
    }

    private List<User> _buildRequest() {
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CreateUsersWithListInputResponse call() throws Exception {
        RequestOperation<List<User>, CreateUsersWithListInputResponse> operation
              = new CreateUsersWithListInput.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
