/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class DeleteUserRequest {
    /**
     * The name that needs to be deleted
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")
    private String username;

    @JsonCreator
    public DeleteUserRequest(
            @Nonnull String username) {
        this.username = Optional.ofNullable(username)
            .orElseThrow(() -> new IllegalArgumentException("username cannot be null"));
    }

    /**
     * The name that needs to be deleted
     */
    public String username() {
        return this.username;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name that needs to be deleted
     */
    public DeleteUserRequest withUsername(@Nonnull String username) {
        this.username = Utils.checkNotNull(username, "username");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteUserRequest other = (DeleteUserRequest) o;
        return 
            Utils.enhancedDeepEquals(this.username, other.username);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            username);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteUserRequest.class,
                "username", username);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String username;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name that needs to be deleted
         */
        public Builder username(@Nonnull String username) {
            this.username = Utils.checkNotNull(username, "username");
            return this;
        }

        public DeleteUserRequest build() {
            return new DeleteUserRequest(
                username);
        }

    }
}
