/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.DeletePet;

public class DeletePetRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final DeletePetRequest.Builder pojoBuilder;
    private DeletePetRequest request;
    private boolean _setterCalled;

    public DeletePetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DeletePetRequest.builder();
    }

    public DeletePetRequestBuilder apiKey(@Nullable String apiKey) {
        this.pojoBuilder.apiKey(apiKey);
        this._setterCalled = true;
        return this;
    }

    public DeletePetRequestBuilder petId(long petId) {
        this.pojoBuilder.petId(petId);
        this._setterCalled = true;
        return this;
    }

    private DeletePetRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public DeletePetResponse call() throws Exception {
        RequestOperation<DeletePetRequest, DeletePetResponse> operation
              = new DeletePet.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
