/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class DeletePetRequest {

    @SpeakeasyMetadata("header:style=simple,explode=false,name=api_key")
    private String apiKey;

    /**
     * Pet id to delete
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")
    private long petId;

    @JsonCreator
    public DeletePetRequest(
            @Nullable String apiKey,
            long petId) {
        this.apiKey = apiKey;
        this.petId = petId;
    }
    
    public DeletePetRequest(
            long petId) {
        this(null, petId);
    }

    public Optional<String> apiKey() {
        return Optional.ofNullable(this.apiKey);
    }

    /**
     * Pet id to delete
     */
    public long petId() {
        return this.petId;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DeletePetRequest withApiKey(@Nullable String apiKey) {
        this.apiKey = apiKey;
        return this;
    }


    /**
     * Pet id to delete
     */
    public DeletePetRequest withPetId(long petId) {
        this.petId = petId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeletePetRequest other = (DeletePetRequest) o;
        return 
            Utils.enhancedDeepEquals(this.apiKey, other.apiKey) &&
            Utils.enhancedDeepEquals(this.petId, other.petId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            apiKey, petId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeletePetRequest.class,
                "apiKey", apiKey,
                "petId", petId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String apiKey;

        private long petId;

        private Builder() {
          // force use of static builder() method
        }

        public Builder apiKey(@Nullable String apiKey) {
            this.apiKey = apiKey;
            return this;
        }

        /**
         * Pet id to delete
         */
        public Builder petId(long petId) {
            this.petId = petId;
            return this;
        }

        public DeletePetRequest build() {
            return new DeletePetRequest(
                apiKey, petId);
        }

    }
}
