/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.DeleteUser;
import org.openapis.openapi.utils.Utils;

public class DeleteUserRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final DeleteUserRequest.Builder pojoBuilder;
    private DeleteUserRequest request;
    private boolean _setterCalled;

    public DeleteUserRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DeleteUserRequest.builder();
    }

    public DeleteUserRequestBuilder username(@Nonnull String username) {
        this.pojoBuilder.username(username);
        this._setterCalled = true;
        return this;
    }

    private DeleteUserRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public DeleteUserResponse call() throws Exception {
        RequestOperation<DeleteUserRequest, DeleteUserResponse> operation
              = new DeleteUser.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
