/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.DeleteOrder;

public class DeleteOrderRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final DeleteOrderRequest.Builder pojoBuilder;
    private DeleteOrderRequest request;
    private boolean _setterCalled;

    public DeleteOrderRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DeleteOrderRequest.builder();
    }

    public DeleteOrderRequestBuilder orderId(long orderId) {
        this.pojoBuilder.orderId(orderId);
        this._setterCalled = true;
        return this;
    }

    private DeleteOrderRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public DeleteOrderResponse call() throws Exception {
        RequestOperation<DeleteOrderRequest, DeleteOrderResponse> operation
              = new DeleteOrder.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
