/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import java.util.List;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.FindPetsByTags;

public class FindPetsByTagsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final FindPetsByTagsRequest.Builder pojoBuilder;
    private FindPetsByTagsRequest request;
    private boolean _setterCalled;

    public FindPetsByTagsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = FindPetsByTagsRequest.builder();
    }

    public FindPetsByTagsRequestBuilder tags(@Nullable List<String> tags) {
        this.pojoBuilder.tags(tags);
        this._setterCalled = true;
        return this;
    }

    private FindPetsByTagsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public FindPetsByTagsResponse call() throws Exception {
        RequestOperation<FindPetsByTagsRequest, FindPetsByTagsResponse> operation
              = new FindPetsByTags.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
