/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.FindPetsByStatus;

public class FindPetsByStatusRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final FindPetsByStatusRequest.Builder pojoBuilder;
    private FindPetsByStatusRequest request;
    private boolean _setterCalled;

    public FindPetsByStatusRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = FindPetsByStatusRequest.builder();
    }

    public FindPetsByStatusRequestBuilder status(@Nullable Status status) {
        this.pojoBuilder.status(status);
        this._setterCalled = true;
        return this;
    }

    private FindPetsByStatusRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public FindPetsByStatusResponse call() throws Exception {
        RequestOperation<FindPetsByStatusRequest, FindPetsByStatusResponse> operation
              = new FindPetsByStatus.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
