/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestlessOperation;

import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetInventory;

public class GetInventoryRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private boolean _setterCalled;

    public GetInventoryRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetInventoryResponse call() throws Exception {
        RequestlessOperation<GetInventoryResponse> operation
            = new GetInventory.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest());
    }
}
