/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetOrderById;

public class GetOrderByIdRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final GetOrderByIdRequest.Builder pojoBuilder;
    private GetOrderByIdRequest request;
    private boolean _setterCalled;

    public GetOrderByIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetOrderByIdRequest.builder();
    }

    public GetOrderByIdRequestBuilder orderId(long orderId) {
        this.pojoBuilder.orderId(orderId);
        this._setterCalled = true;
        return this;
    }

    private GetOrderByIdRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetOrderByIdResponse call() throws Exception {
        RequestOperation<GetOrderByIdRequest, GetOrderByIdResponse> operation
              = new GetOrderById.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
