/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class GetOrderByIdRequest {
    /**
     * ID of order that needs to be fetched
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orderId")
    private long orderId;

    @JsonCreator
    public GetOrderByIdRequest(
            long orderId) {
        this.orderId = orderId;
    }

    /**
     * ID of order that needs to be fetched
     */
    public long orderId() {
        return this.orderId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of order that needs to be fetched
     */
    public GetOrderByIdRequest withOrderId(long orderId) {
        this.orderId = orderId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetOrderByIdRequest other = (GetOrderByIdRequest) o;
        return 
            Utils.enhancedDeepEquals(this.orderId, other.orderId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            orderId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetOrderByIdRequest.class,
                "orderId", orderId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long orderId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of order that needs to be fetched
         */
        public Builder orderId(long orderId) {
            this.orderId = orderId;
            return this;
        }

        public GetOrderByIdRequest build() {
            return new GetOrderByIdRequest(
                orderId);
        }

    }
}
