/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class GetPetByIdRequest {
    /**
     * ID of pet to return
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")
    private long petId;

    @JsonCreator
    public GetPetByIdRequest(
            long petId) {
        this.petId = petId;
    }

    /**
     * ID of pet to return
     */
    public long petId() {
        return this.petId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of pet to return
     */
    public GetPetByIdRequest withPetId(long petId) {
        this.petId = petId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPetByIdRequest other = (GetPetByIdRequest) o;
        return 
            Utils.enhancedDeepEquals(this.petId, other.petId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            petId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetPetByIdRequest.class,
                "petId", petId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long petId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of pet to return
         */
        public Builder petId(long petId) {
            this.petId = petId;
            return this;
        }

        public GetPetByIdRequest build() {
            return new GetPetByIdRequest(
                petId);
        }

    }
}
