/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetPetById;

public class GetPetByIdRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final GetPetByIdRequest.Builder pojoBuilder;
    private GetPetByIdRequest request;
    private boolean _setterCalled;

    public GetPetByIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetPetByIdRequest.builder();
    }

    public GetPetByIdRequestBuilder petId(long petId) {
        this.pojoBuilder.petId(petId);
        this._setterCalled = true;
        return this;
    }

    private GetPetByIdRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetPetByIdResponse call() throws Exception {
        RequestOperation<GetPetByIdRequest, GetPetByIdResponse> operation
              = new GetPetById.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
