/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetUserByName;
import org.openapis.openapi.utils.Utils;

public class GetUserByNameRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final GetUserByNameRequest.Builder pojoBuilder;
    private GetUserByNameRequest request;
    private boolean _setterCalled;

    public GetUserByNameRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetUserByNameRequest.builder();
    }

    public GetUserByNameRequestBuilder username(@Nonnull String username) {
        this.pojoBuilder.username(username);
        this._setterCalled = true;
        return this;
    }

    private GetUserByNameRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetUserByNameResponse call() throws Exception {
        RequestOperation<GetUserByNameRequest, GetUserByNameResponse> operation
              = new GetUserByName.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
