/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.LoginUser;

public class LoginUserRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final LoginUserRequest.Builder pojoBuilder;
    private LoginUserRequest request;
    private boolean _setterCalled;

    public LoginUserRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = LoginUserRequest.builder();
    }

    public LoginUserRequestBuilder username(@Nullable String username) {
        this.pojoBuilder.username(username);
        this._setterCalled = true;
        return this;
    }

    public LoginUserRequestBuilder password(@Nullable String password) {
        this.pojoBuilder.password(password);
        this._setterCalled = true;
        return this;
    }

    private LoginUserRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public LoginUserResponse call() throws Exception {
        RequestOperation<LoginUserRequest, LoginUserResponse> operation
              = new LoginUser.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
