/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.Order;
import org.openapis.openapi.operations.PlaceOrder;

public class PlaceOrderRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private Order request;
    private boolean _setterCalled;

    public PlaceOrderRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PlaceOrderRequestBuilder request(@Nullable Order request) {
        this.request = request;
        return this;
    }

    private Order _buildRequest() {
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public PlaceOrderResponse call() throws Exception {
        RequestOperation<Order, PlaceOrderResponse> operation
              = new PlaceOrder.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
