/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.User;
import org.openapis.openapi.operations.UpdateUser;
import org.openapis.openapi.utils.Utils;

public class UpdateUserRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final UpdateUserRequest.Builder pojoBuilder;
    private UpdateUserRequest request;
    private boolean _setterCalled;

    public UpdateUserRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = UpdateUserRequest.builder();
    }

    public UpdateUserRequestBuilder username(@Nonnull String username) {
        this.pojoBuilder.username(username);
        this._setterCalled = true;
        return this;
    }

    public UpdateUserRequestBuilder user(@Nullable User user) {
        this.pojoBuilder.user(user);
        this._setterCalled = true;
        return this;
    }

    private UpdateUserRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public UpdateUserResponse call() throws Exception {
        RequestOperation<UpdateUserRequest, UpdateUserResponse> operation
              = new UpdateUser.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
