/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.User;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class UpdateUserRequest {
    /**
     * name that needs to be updated
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")
    private String username;

    /**
     * Update an existent user in the store
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private User user;

    @JsonCreator
    public UpdateUserRequest(
            @Nonnull String username,
            @Nullable User user) {
        this.username = Optional.ofNullable(username)
            .orElseThrow(() -> new IllegalArgumentException("username cannot be null"));
        this.user = user;
    }
    
    public UpdateUserRequest(
            @Nonnull String username) {
        this(username, null);
    }

    /**
     * name that needs to be updated
     */
    public String username() {
        return this.username;
    }

    /**
     * Update an existent user in the store
     */
    public Optional<User> user() {
        return Optional.ofNullable(this.user);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * name that needs to be updated
     */
    public UpdateUserRequest withUsername(@Nonnull String username) {
        this.username = Utils.checkNotNull(username, "username");
        return this;
    }


    /**
     * Update an existent user in the store
     */
    public UpdateUserRequest withUser(@Nullable User user) {
        this.user = user;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateUserRequest other = (UpdateUserRequest) o;
        return 
            Utils.enhancedDeepEquals(this.username, other.username) &&
            Utils.enhancedDeepEquals(this.user, other.user);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            username, user);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateUserRequest.class,
                "username", username,
                "user", user);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String username;

        private User user;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * name that needs to be updated
         */
        public Builder username(@Nonnull String username) {
            this.username = Utils.checkNotNull(username, "username");
            return this;
        }

        /**
         * Update an existent user in the store
         */
        public Builder user(@Nullable User user) {
            this.user = user;
            return this;
        }

        public UpdateUserRequest build() {
            return new UpdateUserRequest(
                username, user);
        }

    }
}
