/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.UploadFile;

public class UploadFileRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final UploadFileRequest.Builder pojoBuilder;
    private UploadFileRequest request;
    private boolean _setterCalled;

    public UploadFileRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = UploadFileRequest.builder();
    }

    public UploadFileRequestBuilder petId(long petId) {
        this.pojoBuilder.petId(petId);
        this._setterCalled = true;
        return this;
    }

    public UploadFileRequestBuilder additionalMetadata(@Nullable String additionalMetadata) {
        this.pojoBuilder.additionalMetadata(additionalMetadata);
        this._setterCalled = true;
        return this;
    }

    public UploadFileRequestBuilder requestBody(@Nullable byte[] requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    private UploadFileRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public UploadFileResponse call() throws Exception {
        RequestOperation<UploadFileRequest, UploadFileResponse> operation
              = new UploadFile.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
