/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class UploadFileRequest {
    /**
     * ID of pet to update
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")
    private long petId;

    /**
     * Additional Metadata
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=additionalMetadata")
    private String additionalMetadata;


    @SpeakeasyMetadata("request:mediaType=application/octet-stream")
    private byte[] requestBody;

    @JsonCreator
    public UploadFileRequest(
            long petId,
            @Nullable String additionalMetadata,
            @Nullable byte[] requestBody) {
        this.petId = petId;
        this.additionalMetadata = additionalMetadata;
        this.requestBody = requestBody;
    }
    
    public UploadFileRequest(
            long petId) {
        this(petId, null, null);
    }

    /**
     * ID of pet to update
     */
    public long petId() {
        return this.petId;
    }

    /**
     * Additional Metadata
     */
    public Optional<String> additionalMetadata() {
        return Optional.ofNullable(this.additionalMetadata);
    }

    public Optional<byte[]> requestBody() {
        return Optional.ofNullable(this.requestBody);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of pet to update
     */
    public UploadFileRequest withPetId(long petId) {
        this.petId = petId;
        return this;
    }


    /**
     * Additional Metadata
     */
    public UploadFileRequest withAdditionalMetadata(@Nullable String additionalMetadata) {
        this.additionalMetadata = additionalMetadata;
        return this;
    }


    public UploadFileRequest withRequestBody(@Nullable byte[] requestBody) {
        this.requestBody = requestBody;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UploadFileRequest other = (UploadFileRequest) o;
        return 
            Utils.enhancedDeepEquals(this.petId, other.petId) &&
            Utils.enhancedDeepEquals(this.additionalMetadata, other.additionalMetadata) &&
            Utils.enhancedDeepEquals(this.requestBody, other.requestBody);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            petId, additionalMetadata, requestBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UploadFileRequest.class,
                "petId", petId,
                "additionalMetadata", additionalMetadata,
                "requestBody", requestBody);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long petId;

        private String additionalMetadata;

        private byte[] requestBody;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of pet to update
         */
        public Builder petId(long petId) {
            this.petId = petId;
            return this;
        }

        /**
         * Additional Metadata
         */
        public Builder additionalMetadata(@Nullable String additionalMetadata) {
            this.additionalMetadata = additionalMetadata;
            return this;
        }

        public Builder requestBody(@Nullable byte[] requestBody) {
            this.requestBody = requestBody;
            return this;
        }

        public UploadFileRequest build() {
            return new UploadFileRequest(
                petId, additionalMetadata, requestBody);
        }

    }
}
