/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Consumer;
import org.openapis.openapi.utils.HTTPClient;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.SpeakeasyHTTPClient;
import org.openapis.openapi.utils.Utils;

/**
 * Petstore - OpenAPI 3.1: This is a sample Pet Store Server based on the OpenAPI 3.1 specification.
 * 
 * <p>Some useful links:
 * - [OpenAPI Reference](https://www.speakeasy.com/openapi)
 * - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 * - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * 
 * <p>http://swagger.io - Find out more about Swagger
 */
public class Petstore {


    /**
     * SERVERS contains the list of server urls available to the SDK.
     */
    public static final String[] SERVERS = {
        /**
         * A per-environment API.
         */
        "https://{environment}.petstore.io",
    };

    /**
     * Everything about your Pets
     * 
     * <p>http://swagger.io - Find out more
     */
    private final Pet pet;

    /**
     * Access to Petstore orders
     * 
     * <p>http://swagger.io - Find out more about our store
     */
    private final Store store;

    /**
     * Operations about user
     */
    private final User user;

    /**
     * Everything about your Pets
     * 
     * <p>http://swagger.io - Find out more
     */
    public Pet pet() {
        return pet;
    }

    /**
     * Access to Petstore orders
     * 
     * <p>http://swagger.io - Find out more about our store
     */
    public Store store() {
        return store;
    }

    /**
     * Operations about user
     */
    public User user() {
        return user;
    }

    private SDKConfiguration sdkConfiguration;

    /**
     * The Builder class allows the configuration of a new instance of the SDK.
     */
    public static class Builder {

        private final SDKConfiguration sdkConfiguration = new SDKConfiguration();
        private String serverUrl;
        private String server;
        

        private Builder() {
        }

        /**
         * Allows the default HTTP client to be overridden with a custom implementation.
         *
         * @param client The HTTP client to use for all requests.
         * @return The builder instance.
         */
        public Builder client(HTTPClient client) {
            this.sdkConfiguration.setClient(client);
            return this;
        }
        /**
         * Configures the SDK security to use the provided secret.
         *
         * @param apiKey The secret to use for all requests.
         * @return The builder instance.
         */
        public Builder apiKey(String apiKey) {
            this.sdkConfiguration.setSecuritySource(SecuritySource.of(org.openapis.openapi.models.components.Security.builder()
              .apiKey(apiKey)
              .build()));
            return this;
        }

        /**
         * Configures the SDK to use a custom security source.
         *
         * @param securitySource The security source to use for all requests.
         * @return The builder instance.
         */
        public Builder securitySource(SecuritySource securitySource) {
            Utils.checkNotNull(securitySource, "securitySource");
            this.sdkConfiguration.setSecuritySource(securitySource);
            return this;
        }
        
        /**
         * Overrides the default server URL.
         *
         * @param serverUrl The server URL to use for all requests.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl) {
            this.serverUrl = serverUrl;
            return this;
        }

        /**
         * Overrides the default server URL  with a templated URL populated with the provided parameters.
         *
         * @param serverUrl The server URL to use for all requests.
         * @param params The parameters to use when templating the URL.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl, Map<String, String> params) {
            this.serverUrl = Utils.templateUrl(serverUrl, params);
            return this;
        }
        
        /**
         * Overrides the default server by index.
         *
         * @param serverIdx The server to use for all requests.
         * @return The builder instance.
         */
        public Builder serverIndex(int serverIdx) {
            this.sdkConfiguration.setServerIdx(serverIdx);
            this.serverUrl= SERVERS[serverIdx];
            return this;
        }
        
        /**
         * Overrides the default configuration for retries
         *
         * @param retryConfig The retry configuration to use for all requests.
         * @return The builder instance.
         */
        public Builder retryConfig(RetryConfig retryConfig) {
            this.sdkConfiguration.setRetryConfig(Optional.of(retryConfig));
            return this;
        }

        /**
         * Enables debug logging for HTTP requests and responses, including JSON body content.
         * <p>
         * Convenience method that calls {@link HTTPClient#enableDebugLogging(boolean)}.
         * {@link SpeakeasyHTTPClient} honors this setting. If you are using a custom HTTP client,
         * it is up to the custom client to honor this setting.
         * </p>
         *
         * @param enabled Whether to enable debug logging.
         * @return The builder instance.
         */
        public Builder enableHTTPDebugLogging(boolean enabled) {
            this.sdkConfiguration.client().enableDebugLogging(enabled);
            return this;
        }

        /**
         * ServerEnvironment
         * 
         * <p>The environment name. Defaults to the production environment.
         */
        public enum ServerEnvironment {
            PROD("prod"),
            STAGING("staging"),
            DEV("dev");

            @JsonValue    
            private final String value;

            private ServerEnvironment(String value) {
                this.value = value;
            }

            public String value() {
                return value;
            }

            public static Optional<ServerEnvironment> fromValue(String value) {
                for (ServerEnvironment o: ServerEnvironment.values()) {
                    if (Objects.deepEquals(o.value, value)) {
                        return Optional.of(o);
                    }
                }
                return Optional.empty();
            }
        }
        /**
         * Sets the environment variable for url substitution.
         *
         * @param environment The value to set.
         * @return The builder instance.
         */
        public Builder environment(ServerEnvironment environment) {
            for (Map<String, String> server : this.sdkConfiguration.serverVariables()) {
                if (!server.containsKey("environment")) {
                    continue;
                }
                server.put("environment", environment.toString());
            }

            return this;
        }
        
        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(org.openapis.openapi.utils.Hooks hooks) {
            sdkConfiguration.setHooks(hooks);  
            return this;  
        }
        
        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(Consumer<? super org.openapis.openapi.utils.Hooks> consumer) {
            consumer.accept(sdkConfiguration.hooks());
            return this;    
        }
        
        /**
         * Builds a new instance of the SDK.
         *
         * @return The SDK instance.
         */
        public Petstore build() {
            if (serverUrl == null || serverUrl.isBlank()) {
                serverUrl = SERVERS[0];
                sdkConfiguration.setServerIdx(0);
            }
            sdkConfiguration.setServerUrl(serverUrl);
            return new Petstore(sdkConfiguration);
        }
    }
    
    /**
     * Get a new instance of the SDK builder to configure a new instance of the SDK.
     *
     * @return The SDK builder instance.
     */
    public static Builder builder() {
        return new Builder();
    }

    private Petstore(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.sdkConfiguration.initialize();
        this.pet = new Pet(sdkConfiguration);
        this.store = new Store(sdkConfiguration);
        this.user = new User(sdkConfiguration);
        this.sdkConfiguration = this.sdkConfiguration.hooks().sdkInit(this.sdkConfiguration);
    }
}
