workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/playground-wnq/playground-testing/petstore-oas
targets:
    petstore:
        target: java
        source: petstore-oas
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/playground-wnq/playground-testing/petstore-oas-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
