/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class Tag {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Long id;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    @JsonCreator
    public Tag(
            @JsonProperty("id") @Nullable Long id,
            @JsonProperty("name") @Nullable String name) {
        this.id = id;
        this.name = name;
    }
    
    public Tag() {
        this(null, null);
    }

    public Optional<Long> id() {
        return Optional.ofNullable(this.id);
    }

    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    public static Builder builder() {
        return new Builder();
    }


    public Tag withId(@Nullable Long id) {
        this.id = id;
        return this;
    }


    public Tag withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Tag other = (Tag) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Tag.class,
                "id", id,
                "name", name);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Long id;

        private String name;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nullable Long id) {
            this.id = id;
            return this;
        }

        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        public Tag build() {
            return new Tag(
                id, name);
        }

    }
}
